version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access

networks:
  default:
    external:
      name: app

